server:
  port: 8903
spring:
  application:
    name: ticket
  datasource:
    password: com.gtk.com.xx
    username: root
    url: jdbc:mysql://localhost:3306/db3
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka