server:
  port: 8901
spring:
  application:
    name: user
  datasource:
    password: com.gtk.com.xx
    username: root
    url: jdbc:mysql://localhost:3306/uot-user
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
debug: true