server:
  port: 8902
spring:
  application:
    name: order
  datasource:
    password: com.gtk.com.xx
    username: root
    url: jdbc:mysql://localhost:3306/uot-order
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
debug: true